### ISSUE TITLE
Deploy Error

### ISSUE THREAD

**Issue by YumeMichi** [hexojs/hexo-deployer-rsync#10]
![](http://7sbppu.com1.z0.glb.clouddn.com/QQ20150927-0.png)

**Comment by leesei** [comment]
Please provide deployer-rsync's config.

**Comment by leesei** [comment]
It seems that you don't have `rsync` installed on your system.
Please try this command on your shell:
```sh
$ rsync
```

**Comment by Xuanwo** [comment]
@YumeMichi any update?
