### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by raphaklaus** [hexojs/hexo-deployer-rsync#16]
Hello!

I'm trying to deploy using Windows 10. Before I've had some problems with rsync and ssh commands but installing cygwin seems to solve the issue. But now I'm getting:

```
  FATAL Error: Could not create directory '/home/Raphael/.ssh'.
  Host key verification failed.
```
Since I am not on Linux, these error messages doesn't make sense.
Have someone went through this situation?

**Comment by gboudreau** [comment]
rsync will try to use a SSH key to authentify with the remote server. So you should create a SSH key, store it in a `.ssh` folder in your home directory (/home/Raphael in cygwin), and configure your remote account to allow that SSH key (put the public key in `~/.ssh/authorized_keys` on the remote server, and `chmod 700 ~/.ssh ; chmod 600 ~/.ssh/authorized_keys`).
The goal is to be able to login to the remote host using just "ssh user@hostname" from cygwin.
Once you got that working, `hexo deploy` should work too.
You can probably find more detailed tutorials on configuring SSH keys in Cygwin on Google.

**Comment by raphaklaus** [comment]
@gboudreau thank you! Now the cygwin is configured with ssh and copied to the authorized_keys on the server. Now things make sense! Closing issue since it's ok with Windows. :smiley:

**Comment by zxdawn** [comment]
Although the cygwin is configured with ssh and copied to the authorized_keys on the server. I still get:
```
INFO  Deploying: rsync
Could not create directory '/home/36391/.ssh'.
Host key verification failed. 
```
Could you help me?
