### ISSUE TITLE
Rsync deploy error

### ISSUE THREAD

**Issue by Remonli** [hexojs/hexo-deployer-rsync#19]
Hello, got error when deploy with rsync while rsync works well when type in bash

```
INFO  Deploying: rsync
The source and destination cannot both be remote.
rsync error: syntax or usage error (code 1) at /home/lapo/package/rsync-3.0.9-1/src/rsync-3.0.9/main.c(1148) [Receiver=3.0.9]
FATAL Something's wrong. Maybe you can find the solution here: http://hexo.io/docs/troubleshooting.html
Error: The source and destination cannot both be remote.
rsync error: syntax or usage error (code 1) at /home/lapo/package/rsync-3.0.9-1/src/rsync-3.0.9/main.c(1148) [Receiver=3.0.9]

    at ChildProcess.<anonymous> (D:\Hexo\node_modules\hexo-deployer-rsync\node_modules\hexo-util\lib\spawn.js:37:17)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at ChildProcess.cp.emit (D:\Hexo\node_modules\cross-spawn\lib\enoent.js:40:29)
    at maybeClose (internal/child_process.js:852:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
FATAL The source and destination cannot both be remote.
rsync error: syntax or usage error (code 1) at /home/lapo/package/rsync-3.0.9-1/src/rsync-3.0.9/main.c(1148) [Receiver=3.0.9]

Error: The source and destination cannot both be remote.
rsync error: syntax or usage error (code 1) at /home/lapo/package/rsync-3.0.9-1/src/rsync-3.0.9/main.c(1148) [Receiver=3.0.9]

    at ChildProcess.<anonymous> (D:\Hexo\node_modules\hexo-deployer-rsync\node_modules\hexo-util\lib\spawn.js:37:17)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at ChildProcess.cp.emit (D:\Hexo\node_modules\cross-spawn\lib\enoent.js:40:29)
    at maybeClose (internal/child_process.js:852:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)              
```

hexo version

```
hexo: 3.2.0
hexo-cli: 1.0.2
os: Windows_NT 10.0.10586 win32 x64
http_parser: 2.7.0
node: 6.2.2
v8: 5.0.71.52
uv: 1.9.1
zlib: 1.2.8
ares: 1.10.1-DEV
icu: 57.1
modules: 48
openssl: 1.0.2h

```

**Comment by Xuanwo** [comment]
`The source and destination cannot both be remote.`
看起来是配置问题？印象中rsync插件有过更新。

**Comment by Rememberli** [comment]
我的hexo 环境是win10 x64 + cygwin(mobaXterm) + nodejs 6.2.2 , 
hexo windows路径是 D:\hexo\ , cygwin 路径 /drives/d/hexo/

**Comment by Xuanwo** [comment]
paste your config please.

**Comment by Rememberli** [comment]
Rsync deploy 部分的配置如下：
```
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: rsync
  host: www.myhost.com
  user: user
  root: /home/user/www
  port: 22
  delete: true
  verbose: true
  ignore_errors: false
```

**Comment by Xuanwo** [comment]
从我的理解来看，可能rsync把两个地址都是识别成远端地址了。
你把 https://github.com/hexojs/hexo-deployer-rsync/blob/master/lib/deployer.js#L35 改成 `'public'` 看看能否使用。

ref: http://superuser.com/questions/337958/why-cwrsync-doesnt-work-on-windows

**Comment by Rememberli** [comment]
报错信息确实是两个地址都认成远端地址了，但不知道是不是deploy.js 引起的。
按你说的改了还是报错如下，不知道是不是别的js模块不兼容nodejs v6 引起的？
我不是程序员，实在是搞不懂，但之前没有npm upgrade 的时候就完全没问题,
而现在退回到nodejs v4 还是报错，足见应该是某个模块的问题，而不是nodejs
版本的问题。

```
ERROR Plugin load failed: hexo-deployer-rsync
D:\Hexo\node_modules\hexo-deployer-rsync\lib\deployer.js:35
    public,
    ^^^^^^
SyntaxError: Unexpected strict mode reserved word
```

**Comment by Xuanwo** [comment]
public 要加引号

我先去吃个饭，回来再看看。

Rememberli <notifications@github.com>于2016年7月1日 周五 18:02写道：

> 报错信息确实是两个地址都认成远端地址了，但不知道是不是deploy.js 引起的。
> 按你说的改了还是报错如下，不知道是不是别的js模块不兼容nodejs v6 引起的？
> 我不是程序员，实在是搞不懂，但之前没有npm upgrade 的时候就完全没问题,
> 而现在退回到nodejs v4 还是报错，足见应该是某个模块的问题，而不是nodejs
> 版本的问题。
>
> ERROR Plugin load failed: hexo-deployer-rsync
> D:\Hexo\node_modules\hexo-deployer-rsync\lib\deployer.js:35
>     public,
>     ^^^^^^
> SyntaxError: Unexpected strict mode reserved word
>
> —
> You are receiving this because you commented.
>
>
> Reply to this email directly, view it on GitHub
> <https://github.com/hexojs/hexo-deployer-rsync/issues/19#issuecomment-229908871>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AFGoeqCvXtyopjuLPLDaMQYyivHP1X73ks5qROWwgaJpZM4I8fRk>
> .
>
-- 
Best Regards
Xuanwo

**Comment by Rememberli** [comment]
this.public_dir -> 'public' ， 这样确实可以了， 好奇怪，谢谢啦。

**Comment by Xuanwo** [comment]
刚才那个是给你提供的临时解决方案，具体的代码修改我可能还要再看看怎么改，大概要找找`this.public_dir`在win下面到底生成了什么。

**Comment by willin** [comment]
问题解决了吗

**Comment by Xuanwo** [comment]
暂时还没有，我本周末会看一下。

**Comment by zklhp** [comment]
#21 @Xuanwo 看起来你没有看。你看看这样可以不可以。

**Comment by Xuanwo** [comment]
@tommy351 Please push a new version to npm which fix error on Win.

**Comment by Rememberli** [comment]
@tommy351 @Xuanwo 

Still not yet updated to npm.
