### ISSUE TITLE
Failed to deploy with rsync, connection refused. Require npm package update

### ISSUE THREAD

**Issue by JoySR** [hexojs/hexo-deployer-rsync#23]
same problem as [#20](https://github.com/hexojs/hexo-deployer-rsync/issues/20)。

I changed `/node_modules/hexo-deployer-rsync/lib/deployer.js` and problem solved.

However, I think an up-to-date npm package is more friendly, so that users don't need to edit each file or clone from GitHub into each folder if they maintain more than one hexo-project. 

Thanks. :)

**Comment by stevenjoezhang** [comment]
New version released https://github.com/hexojs/hexo-deployer-rsync/releases/tag/1.0.0
