### ISSUE TITLE
release version 0.1.3 is not on npm

### ISSUE THREAD

**Issue by jkzing** [hexojs/hexo-deployer-rsync#26]
The release version 0.1.3 in master branch is not on npm.

Since it has been almost 2 months from 0.1.3 released, did you guys forgot to publish it?

**Comment by NoahDragon** [comment]
This is a known issue currently, which no active contributors have the permission to update the npm repo.

**Comment by Remonli** [comment]
So who has the permission ? @tommy351 or somebody else ?

**Comment by NoahDragon** [comment]
@Remonli Thanks for poke this issue. I tried to find the repo that I add release but hadn't publish to npm. Here it is.

Now it is 0.1.3 on NPM. Enjoy!
