### ISSUE TITLE
ERROR of 'hexo deploy'

### ISSUE THREAD

**Issue by zxdawn** [hexojs/hexo-deployer-rsync#28]
Although the cygwin is configured with ssh and copied to the authorized_keys on the server. I still get:

```
INFO  Deploying: rsync
Could not create directory '/home/36391/.ssh'.
Host key verification failed. 
```

Here is my settings:
```
cygwin:
location: E:\cygwin\home\blog
npm version: 3.10.10
hexo configuration:
deploy:
  type: rsync
  host: www.myhost.com
  user: root
  root: /root/blog
  port: 22
```

Could you help me?

**Comment by n0vad3v** [comment]
Seems the problem is caused by SSH key, possible solutions might be:
1.`chmod` the .ssh/authorize_keys file.[Reference](https://www.digitalocean.com/community/tutorials/how-to-use-ssh-keys-with-digitalocean-droplets)
2.Check key status in cygwin environment.

**Comment by zxdawn** [comment]
I'm using Ubuntu on windows now. It works fine~
