### ISSUE TITLE
Error: spawn rsync ENOENT

### ISSUE THREAD

**Issue by dazjean** [hexojs/hexo-deployer-rsync#29]
deploy:
  type: rsync
  host: XXXXXX.my3w.com
  user: XXXXXXXXFTP
  root: /htdocs
  port: 21
-------
"hexo": "^3.2.0",
"hexo-deployer-rsync": "^0.1.3",

----npm run delpoy---------logs-----------
["--delete","-v","-az","-e","ssh -p 22","public/","XXXXXXXFTP@XXXXXXXX5011                                                                                                                                                                                               8.my3w.com:/htdocs"] // debug console.log params in deployer.js with line 48
'rsync' ▒▒▒▒▒ڲ▒▒▒▒ⲿ▒▒▒Ҳ▒▒▒ǿ▒▒▒▒еĳ▒▒▒
▒▒▒▒▒▒▒▒▒ļ▒▒▒
------------{"command":"C:\\Windows\\system32\\cmd.exe","args":["/s","/c","\"rsy                                                                                                                                                                                               nc \"--delete\" \"-v\" \"-az\" \"-e\" \"ssh -p 22\" \"public/\" \"qxuXXXXXXXXXF                                                                                                                                                                                               TP@qxuXXXXX8.my3w.com:/htdocs\"\""],"options":{"verbose":true,"windowsVerbat                                                                                                                                                                                               imArguments":true},"original":"rsync"} // debug console.log parsedin enoent.js with line 45
FATAL Something's wrong. Maybe you can find the solution here: http://hexo.io/do                                                                                                                                                                                               cs/troubleshooting.html
Error: spawn rsync ENOENT
    at notFoundError (D:\myweb\blog\node_modules\cross-spawn\lib\enoent.js:11:11                                                                                                                                                                                               )
    at verifyENOENT (D:\myweb\blog\node_modules\cross-spawn\lib\enoent.js:47:16)
    at ChildProcess.cp.emit (D:\myweb\blog\node_modules\cross-spawn\lib\enoent.j                                                                                                                                                                                               s:33:19)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
npm ERR! code ELIFECYCLE
npm ERR! errno 2
----------------------------------------------end---------------------
enoent.js:
isWin=true ,status=1 
if (isWin && status === 1 && !parsed.file) {
        return notFoundError(parsed.original, 'spawn');
}

**Comment by baoang** [comment]
也遇到同样的问题了，不知是怎么回事，估计是版本冲突？

**Comment by wanzhiyu** [comment]
请问如何解决的？

**Comment by dazjean** [comment]
当时没有处理，因为我看FTP服务器上已经把文件传递上去了

**Comment by dazjean** [comment]
当时没有处理，因为我看FTP服务器上已经把文件传递上去了
