### ISSUE TITLE
'rsync' is not recognized as an internal or external command, operable program or batch file.

### ISSUE THREAD

**Issue by baoang** [hexojs/hexo-deployer-rsync#30]
在几种部署方案中，发现rsync和sftp的方式可能对我更容易办些（但sftp的方式我不知道privatekey和passphrase怎么填），于是就采用rsync的方式。

在网上也查到一篇[说明文章](https://www.jianshu.com/p/605c3d32cab9)，一步步的讲授，照着做了。但是结果没成功，报出错误来，就是标题中的提示。

搜索了下这里也有同样遇到问题的网友，但仍然未找出问题出在哪里，希望能有人及时指出来。

**Comment by 7ummy** [comment]
rsync在VPS上还需要有一些配置，比如SSH登录验证，编辑/etc目录下rsync文件(具体自己find文件)，配置好了以后rsync才真正启动。

**Comment by baoang** [comment]
多谢解释。

原来如此，看来这个还是比较麻烦。

**Comment by n0vad3v** [comment]
字面翻译了一下rsync不是内部或外部命令。你是不是尝试在Windows上面使用rsync？
就我了解如果要在windows上面用rsync的话好像需要cygwin。

**Comment by baoang** [comment]
对，我在WIN10上面架了个Hexo然后尝试着写博客，写完觉得或许也能不用一个一个文件用FTP上传，于是就查看网上的说明，官方文档最后一部分就是部署，觉得比自己一个一个文件上传要好得多。

没想到WINDOWS这么不争气，配置的部分要比其它系统麻烦。

**Comment by n0vad3v** [comment]
哈，Windows的确在主流服务器管理方面的确很麻烦。
如果您有VPS的话，或许可以考虑如下方式：
1.在VPS上安装Hexo，网页服务器监听Hexo下的`/public`目录，把本地`/source`文件夹下的内容同步上去后，SSH上去`hexo g`。
2.本地`hexo g`好后用WinSCP这类图形化工具把本地`/public`目录下的文件rsync上去，一般不会遇到SSH Key的问题。

**Comment by baoang** [comment]
今天偶然的，发现一条消息，称Windows 10是可以[在optional feature里加装OpenSSH](https://www.howtogeek.com/336775/how-to-enable-and-use-windows-10s-built-in-ssh-commands/)的。这是否意味着不用直接进VPS或者安装本机的Linux以配置环境了？

**Comment by stevenjoezhang** [comment]
用子系统也很方便。
