### ISSUE TITLE
Deploying to IPv6 host doesn't work in macOS

### ISSUE THREAD

**Issue by a342191555** [hexojs/hexo-deployer-rsync#80]
Hi, I've met a problem when deploy my blog to an IPv6 host with rsync plugin in macOS.
The config file like :
```
deploy:
- type: rsync
  host: '[::1]'
  user: root
  root: /PATH/TO/html
```
It seems the deployer will generate params for sync like 
```rsync -az /PATH/FROM/LOCAL/public root@[::1]:/PATH/TO/html```

I've comfirmed it DO work well in rsync(version 3.1.3, protocol version 31) in most Linux distributions, however, the version of the built-in ```rsync``` in macOS(Big Sur 11.6, current latest version) was 2.6.8(protocol version 29), which does not support  the syntax of ```root@[::1]```.

There may be 2 solutions:
- Use an alternative way to call ```sync```: use the ```ssh -l user``` option, [metioned here](https://serverfault.com/a/890087).
 The ```sync``` command will then be called like ```rsync -az -e 'ssh -l root' /PATH/FROM/LOCAL/public [::1]:/PATH/TO/html```.
- Upgrade the ```rsync``` tool with [homebrew](https://formulae.brew.sh/formula/rsync) (or else).

I can create a PR to fix this issue with the first solution if you would, while I am now using the other.

**Comment by SukkaW** [comment]
> * Use an alternative way to call `sync`: use the `ssh -l user` option, [metioned here](https://serverfault.com/a/890087).
>   The `sync` command will then be called like `rsync -az -e 'ssh -l root' /PATH/FROM/LOCAL/public [::1]:/PATH/TO/html`.

What happens if the `rsync` is not running under `root`?

**Comment by a342191555** [comment]
> What happens if the `rsync` is not running under `root`?

```ssh -l root``` in ```rsync -e ```will use user ```root``` , just like ```ssh root@::1```.
If my config file is:
```
deploy:
- type: rsync
  host: '[::1]'
  user: my_name
  root: /PATH/TO/html
```
The ```rsync``` command should be ```rsync -az -e 'ssh -l my_name' /PATH/FROM/LOCAL/public [::1]:/PATH/TO/html```

**Comment by stevenjoezhang** [comment]
I'm closing this issue since it's related to the version of rsync itself. Maybe you can add the docs about installing rsync tool with [homebrew](https://formulae.brew.sh/formula/rsync) to README.

**Comment by a342191555** [comment]
Now I am in `macOS Ventura`, seems Apple has upgraded `rsync` to `version 3.2.7  protocol version 31`, this issue is now fixed by "upgrading macOS" LOL.
